      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '14.x'
        displayName: 'Install Node.js'

      - script: |
          npm install @hapi/hapi@19 @hapi/bell@12 @hapi/boom@9 @hapi/cookie@11 @hapi/inert@6 @hapi/joi@17 @hapi/vision@6 dotenv@8 ejs@3 postgres@1
#          npm --save-dev nodemon@2
        displayName: 'npm install and build'

#       - task: ArchiveFiles@2
#         displayName: 'Archive files'
#         inputs:
#           rootFolderOrFile: '$(Build.SourcesDirectory)'
#           includeRootFolder: false
#           archiveType: zip
#           archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
#           replaceExistingArchive: true
#       - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
#         artifact: drop

